FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV CC clang-17
ENV CXX clang++-17

# Install needed base packages
RUN apt-get update && apt-get install -y    \
    git cmake ninja-build build-essential   \
    python3-minimal python3-pip clang       \
    wget software-properties-common

# Setup LLVM 17 for kcfi
RUN wget https://apt.llvm.org/llvm.sh
RUN chmod u+x llvm.sh
RUN ./llvm.sh 17
RUN rm llvm.sh

CMD ["bash"]
