services:
  ubuntu14:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu14
    container_name: ubuntu14
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always

  ubuntu16:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu16
    container_name: ubuntu16
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always

  ubuntu18:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu18
    container_name: ubuntu18
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always

  ubuntu20:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu20
    container_name: ubuntu20
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always

  ubuntu22:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu22
    container_name: ubuntu22
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always
