FROM ubuntu:16.04

# Install required packages
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    python3 \
    curl clang wget binutils-dev

CMD ["bash"]
