services:
  mcfi:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu14
    container_name: mcfi
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always

  typro:
    build:
      context: ../policies/TyPro-CFI/
      dockerfile: Dockerfile
    container_name: typro
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always

  main:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu20
    container_name: main
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always

  custom:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu22
    container_name: custom
    volumes:
      - ../:/mnt/shared:z
      - /home/rombertus-laptop/spec:/mnt/spec:z
    tty: true
    restart: always
