FROM ubuntu:14.04

# Install required packages
RUN apt-get update && apt-get install -y \
    build-essential cmake ninja-build python3 curl wget nano g++-multilib flex \
    bison libtool subversion git cmake autoconf automake texinfo texi2html \
    libtinfo5 gyp

CMD ["bash"]
